### PR TITLE
Updated file structure

### PR DESCRIPTION
**Pull request by joelfischerr**
As most of the files are not used very often by the user, I propose to put them into a separate folder like this:

```
├── Kartei
│   ├── kartei.a5printstyle.tex
│   ├── kartei.a5printstylerotation.tex
│   ├── kartei.a6printstyle.tex
│   ├── kartei.a6printstylerotation.tex
│   ├── kartei.a7printstyle.tex
│   ├── kartei.a7printstylerotation.tex
│   ├── kartei.a8printstyle.tex
│   ├── kartei.a8printstylerotation.tex
│   ├── kartei.a9printstyle.tex
│   ├── kartei.a9printstylerotation.tex
│   ├── kartei.cls
│   ├── kartei.pageshipout.tex
│   ├── kartei.print.tex
│   ├── kartei.tableofcontents.tex
│   └── texput.log
├── Readme.md
├── beispiel.pdf
├── beispiel.tex
├── manual.pdf
├── manual.tex
├── manualexample1.pdf
└── manualexample1.tex
```

### CODE REVIEW

**Comment by kellertuer** [comment]
I would not put kartei.cls into a subfolder because that's the main class file (at least I'm not sure about the general CTAN convention here). For the remaining files I think It's a matter of taste, I don't think that are too many files in one folder.

**Comment by joelfischerr** [comment]
My reasoning behind moving everything into a subfolder was that things that belong together should go together. While the actual content of the flashcards is in the top folder, everything in the Kartei folder is only necessary behind the scenes.

The folder is not yet what I'd call crowded, but as soon as multiple documents with flashcards are created it becomes crowded very fast.

**Comment by kellertuer** [comment]
My recommendation would be to install that package in the TeX tree anyways.

**Comment by joelfischerr** [comment]
In my opinion the problem with that is, that it makes sharing a bit more difficult. As additional to knowing about basic LaTex now people have to learn about TeX tree.

**Pull request closed without merging**
